{{- $hasFilesystemEngine := include "kms.hasFilesystemEngine" . | eq "true" -}}
apiVersion: apps/v1
{{- if $hasFilesystemEngine }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:  
  name: kms
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: kms
spec:
  replicas: 1
{{- if $hasFilesystemEngine }}
  serviceName: "kms"
{{- end }}
  selector:
    matchLabels:
      app: kms
  template:
    metadata:
      labels:
        app: kms
    spec:
      containers:
        - name: kms
          image: {{ .Values.services.kms.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          tty: true
          env:
            {{- range .Values.services.kms.cryptoEngines.engines }}
            {{- if eq .type "pkcs11" }}
            {{- if .module_extra_options.env }}
            {{- range $key, $value := .module_extra_options.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: api-config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
            - name: golang-engine-storage
              mountPath: /crypto/fs
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: api-config
          configMap:  
            name: kms-config
{{- if $hasFilesystemEngine }}
  volumeClaimTemplates:
  # Filesystem engine is configured, using PVC for persistent storage
  - metadata:
      name: golang-engine-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: null
      resources:
        requests:
          storage: 1Gi
{{- end }}
