apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: api-kms
  namespace: {{ .Release.Namespace }}
  labels:
    auth: "private"
spec:
  parentRefs:
    - name: eg
      sectionName: https  # The specific listener
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /api/kms/
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: "/"
      backendRefs:
        - name: kms
          port: 8085
