kind: ConfigMap
apiVersion: v1
metadata:
  name: kms-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    logs:
      level: "debug"

    server:
      log_level: "debug"
      health_check: false
      listen_address: "0.0.0.0"
      port: 8085
      protocol: "http" #http | https
    
    publisher_event_bus:
      log_level: "debug"
      enabled: true
      provider: amqp
      protocol: amqp #amqp | amqps
      hostname: {{ $.Values.amqp.hostname }}
      port: {{ $.Values.amqp.port }}
      basic_auth:
        enabled: true
        username: {{ $.Values.amqp.username }}
        password: {{ $.Values.amqp.password }}

    storage:
      log_level: "info"
      provider: "postgres" #couch_db | postgres | dynamo_db
      hostname: {{ $.Values.postgres.hostname }}
      port: {{ $.Values.postgres.port }}
      username: "{{ $.Values.postgres.username }}"
      password: "{{ $.Values.postgres.password }}"

    crypto_engines:
      migrate_keys_format: false
      log_level: "trace"
      default_id: {{ .Values.services.kms.cryptoEngines.defaultEngineID }}
      engines:      
        {{ .Values.services.kms.cryptoEngines.engines | toYaml | indent 4 | nindent 4 | trim  }}
